### PR TITLE
HY-1827 - Set src/ as the lib directory for jspm

### PR DESCRIPTION
**Pull request by tomconnell-wf**
# Blocked - I assume I need to figure out the correct travis CI ssh credentials to embed in .travis.yml.

See http://docs.travis-ci.com/user/environment-variables/#Secure-Variables
# Problem

Since requireJS aliases are set to allow referencing files in src/, without typing src/, jspm consumers will get 404s when attempting to use the require() functions.
# Solution

Instruct jspm, via package.json, that src/ is the lib directory.  This change allows jspm to automagically work with the existing code, and those requireJS aliases. 
# How to Test

This is just a config change, so there is nothing to functionally test.

### CODE REVIEW

**Comment by trentgrover-wf** [comment]
@tomconnell-wf @robbecker-wf fixed this so travis CI will pass.  If you want sauce labs stuff to work, this repo is missing all of the karma sauce config

**Comment by robbecker-wf** [comment]
@trentgrover-wf it's on my list but below some other things unfortunately ... I'm having trouble getting the credentials and stuff right. Maybe give me a hand some time?

**Comment by trentgrover-wf** [comment]
what browsers did you want to sauce labs to check for this lib?

**Comment by robbecker-wf** [comment]
The usuals ... IE9+, Chrome, Firefox, Safari

**Comment by trentgrover-wf** [comment]
+1
@robbecker-wf @maxwellpeterson-wf @evanweible-wf @jayudey-wf 
let's get this merged so that this has travis CI support enabled

**Comment by evanweible-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Pull request closed without merging**
